In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('Nike_data.csv')

In [6]:
df

,Link,Name,Subtitle,Sale_Price,Full_Price
0,https://www.nike.com/in/t/air-force-1-07-lx-sh...,Nike Air Force 1 '07 LXWomen's Shoes,Women's Shoes,₹ 11 297.00,MRP : ₹ 11 895.00
1,https://www.nike.com/in/t/dunk-low-lx-shoes-tV...,Nike Dunk Low LXWomen's Shoes,Women's Shoes,₹ 11 297.00,MRP : ₹ 11 895.00
2,https://www.nike.com/in/t/dunk-low-shoes-wbxcm...,Nike Dunk LowWomen's Shoes,Women's Shoes,₹ 7 877.00,MRP : ₹ 8 295.00
3,https://www.nike.com/in/t/court-vision-low-nex...,Nike Court Vision Low Next NatureWomen's Shoes,Women's Shoes,₹ 6 737.00,MRP : ₹ 7 095.00
4,https://www.nike.com/in/t/sportswear-photo-t-s...,Nike SportswearMen's Photo T-Shirt,Men's Photo T-Shirt,₹ 2 557.00,MRP : ₹ 2 695.00
...,...,...,...,...,...
1193,https://www.nike.com/in/t/racing-ankle-socks-5...,Nike RacingAnkle Socks,Ankle Socks,₹ 1 327.00,MRP : ₹ 1 395.00
1194,https://www.nike.com/in/t/dri-fit-trail-runnin...,Nike Dri-FITTrail-Running Crew Socks,Trail-Running Crew Socks,₹ 1 417.00,MRP : ₹ 1 495.00
1195,https://www.nike.com/in/t/acg-everyday-cushion...,Nike ACG EverydayCushioned Crew Socks (1 Pair),Cushioned Crew Socks (1 Pair),₹ 1 227.00,MRP : ₹ 1 295.00
1196,https://www.nike.com/in/t/strike-football-crew...,Nike StrikeFootball Crew Socks,Football Crew Socks,₹ 847.00,MRP : ₹ 895.00
1197,https://www.nike.com/in/t/everyday-cushioned-t...,Nike Everyday CushionedTraining Low Socks (6 P...,Training Low Socks (6 Pairs),₹ 947.00,MRP : ₹ 995.00

In [8]:
df['Sale_Price']=df['Sale_Price'].str.replace('₹' , '')

In [12]:
df

,Link,Name,Subtitle,Sale_Price,Full_Price
0,https://www.nike.com/in/t/air-force-1-07-lx-sh...,Nike Air Force 1 '07 LXWomen's Shoes,Women's Shoes,11 297.00,11 895.00
1,https://www.nike.com/in/t/dunk-low-lx-shoes-tV...,Nike Dunk Low LXWomen's Shoes,Women's Shoes,11 297.00,11 895.00
2,https://www.nike.com/in/t/dunk-low-shoes-wbxcm...,Nike Dunk LowWomen's Shoes,Women's Shoes,7 877.00,8 295.00
3,https://www.nike.com/in/t/court-vision-low-nex...,Nike Court Vision Low Next NatureWomen's Shoes,Women's Shoes,6 737.00,7 095.00
4,https://www.nike.com/in/t/sportswear-photo-t-s...,Nike SportswearMen's Photo T-Shirt,Men's Photo T-Shirt,2 557.00,2 695.00
...,...,...,...,...,...
1193,https://www.nike.com/in/t/racing-ankle-socks-5...,Nike RacingAnkle Socks,Ankle Socks,1 327.00,1 395.00
1194,https://www.nike.com/in/t/dri-fit-trail-runnin...,Nike Dri-FITTrail-Running Crew Socks,Trail-Running Crew Socks,1 417.00,1 495.00
1195,https://www.nike.com/in/t/acg-everyday-cushion...,Nike ACG EverydayCushioned Crew Socks (1 Pair),Cushioned Crew Socks (1 Pair),1 227.00,1 295.00
1196,https://www.nike.com/in/t/strike-football-crew...,Nike StrikeFootball Crew Socks,Football Crew Socks,847.00,895.00
1197,https://www.nike.com/in/t/everyday-cushioned-t...,Nike Everyday CushionedTraining Low Socks (6 P...,Training Low Socks (6 Pairs),947.00,995.00

In [11]:
df['Full_Price']=df['Full_Price'].str.replace('₹' , '').str.replace('MRP :','')

In [18]:
df['Name'][df['Name'].str.contains('Shoes')]

0                 Nike Air Force 1 '07 LXWomen's Shoes
1                        Nike Dunk Low LXWomen's Shoes
2                           Nike Dunk LowWomen's Shoes
3       Nike Court Vision Low Next NatureWomen's Shoes
5                      Nike Terminator HighMen's Shoes
                             ...
1156              Nike Metcon 9 AMPMen's Workout Shoes
1157         Nike Structure 25Men's Road Running Shoes
1175         Nike Flex Plus 2Older Kids' Running Shoes
1179              Nike Metcon 9 AMPMen's Workout Shoes
1180         Nike Structure 25Men's Road Running Shoes
Name: Name, Length: 527, dtype: object

In [35]:
df['Shoes'] = df['Name'].apply(lambda x: x if 'Shoes' in x else '')

In [48]:
df['Full_Price']=df['Full_Price'].str.replace(' ','').str.replace('00','').str.replace('.', '')

In [49]:
df.head()

,Link,Name,Subtitle,Sale_Price,Full_Price,Shoes
0,https://www.nike.com/in/t/air-force-1-07-lx-sh...,Nike Air Force 1 '07 LXWomen's Shoes,Women's Shoes,11297,11895,Nike Air Force 1 '07 LXWomen's Shoes
1,https://www.nike.com/in/t/dunk-low-lx-shoes-tV...,Nike Dunk Low LXWomen's Shoes,Women's Shoes,11297,11895,Nike Dunk Low LXWomen's Shoes
2,https://www.nike.com/in/t/dunk-low-shoes-wbxcm...,Nike Dunk LowWomen's Shoes,Women's Shoes,7877,8295,Nike Dunk LowWomen's Shoes
3,https://www.nike.com/in/t/court-vision-low-nex...,Nike Court Vision Low Next NatureWomen's Shoes,Women's Shoes,6737,7095,Nike Court Vision Low Next NatureWomen's Shoes
4,https://www.nike.com/in/t/sportswear-photo-t-s...,Nike SportswearMen's Photo T-Shirt,Men's Photo T-Shirt,2557,2695,

In [58]:
df['Subtitle'].isnull().sum()

0

In [69]:
df['Sale_Price']=df['Sale_Price'].astype('int')

In [81]:
df[(df['Sale_Price']>2000) & (df['Subtitle'] =="Women's Shoes")]

,Link,Name,Subtitle,Sale_Price,Full_Price,Shoes
0,https://www.nike.com/in/t/air-force-1-07-lx-sh...,Nike Air Force 1 '07 LXWomen's Shoes,Women's Shoes,11297,11895,Nike Air Force 1 '07 LXWomen's Shoes
1,https://www.nike.com/in/t/dunk-low-lx-shoes-tV...,Nike Dunk Low LXWomen's Shoes,Women's Shoes,11297,11895,Nike Dunk Low LXWomen's Shoes
2,https://www.nike.com/in/t/dunk-low-shoes-wbxcm...,Nike Dunk LowWomen's Shoes,Women's Shoes,7877,8295,Nike Dunk LowWomen's Shoes
3,https://www.nike.com/in/t/court-vision-low-nex...,Nike Court Vision Low Next NatureWomen's Shoes,Women's Shoes,6737,7095,Nike Court Vision Low Next NatureWomen's Shoes
6,https://www.nike.com/in/t/air-jordan-1-high-me...,Air Jordan 1 High Method of MakeWomen's Shoes,Women's Shoes,13487,14195,Air Jordan 1 High Method of MakeWomen's Shoes
...,...,...,...,...,...,...
1113,https://www.nike.com/in/t/nikecourt-legacy-can...,NikeCourt Legacy CanvasWomen's Shoes,Women's Shoes,3797,3995,NikeCourt Legacy CanvasWomen's Shoes
1118,https://www.nike.com/in/t/jordan-stadium-90-sh...,Jordan Stadium 90Women's Shoes,Women's Shoes,12157,12795,Jordan Stadium 90Women's Shoes
1136,https://www.nike.com/in/t/air-max-pulse-shoes-...,Nike Air Max PulseWomen's Shoes,Women's Shoes,13297,13995,Nike Air Max PulseWomen's Shoes
1137,https://www.nike.com/in/t/nikecourt-legacy-can...,NikeCourt Legacy CanvasWomen's Shoes,Women's Shoes,3797,3995,NikeCourt Legacy CanvasWomen's Shoes
1142,https://www.nike.com/in/t/jordan-stadium-90-sh...,Jordan Stadium 90Women's Shoes,Women's Shoes,12157,12795,Jordan Stadium 90Women's Shoes